name: functions
description: An example application to deploy dart on aws lambda through sst framework using custom runtime.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  aws_lambda_dart_runtime:
    git:
      url: https://github.com/katallaxie/aws-lambda-dart-runtime
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
